### ISSUE TITLE
'D' operation doesn't work on keyboard for 3D Semantic Segmentation section

### ISSUE THREAD

**Issue by hjh02** [scaleapi/nucleus-python-client#169]
I don't know where the appropriate place to give feedback is, so I leave an issue on the repo that's been recently updated. Please send this to the relevant department.

On your front page [scale.com](https://scale.com), in the "Scale Advanced Annotations" section, there is a slideshow for all the showcases of what your company has done. 

Among them, in the first "3D Semantic Segmentation" showcase, the 'D' operation doesn't work on the keyboard; it works on manual click. Other operations such as Q, W, E, A, S work normally on the keyboard as well as on manual click. 

P.S. Of course, I have checked that the D letter works totally fine in other cases, even with writing this Github issue. Thanks.

**Comment by gatli** [comment]
Hmm, I can't seem to reproduce your problem. What platform are you on? I.e. browser, OS, etc... ?
