### ISSUE TITLE
Threshold for False Positive and False Negatives

### ISSUE THREAD

**Issue by MaximilianBoemer** [scaleapi/nucleus-python-client#17]
Currently if I display the patches and want to see FNs are FPs, I only get the patches which have 0 overlap. It would be useful to be able to define a threshold. E.g. all boxes with a threshold < 0.5 are a FP/FN.

**Comment by ardila** [comment]
<img width="224" alt="Screen Shot 2021-09-08 at 9 51 55 AM" src="https://user-images.githubusercontent.com/2701347/132551657-1a363340-699a-420e-8005-a2bbce7e9e8f.png">
This is now possible in Nucleus V2
