### ISSUE TITLE
model_run.predict(payload) not working for me.

### ISSUE THREAD

**Issue by MaximilianBoemer** [scaleapi/nucleus-python-client#21]
Getting error: `{'status_code': 500, 'error': 'An error has occurred, please reach out to support@scale.com if you need assistance.'}`

When running:
`detection = [{'label': '11004', 'type': 'box', 'geometry': {'x': 301.78, 'y': 602.9, 'width': 153.45000000000005, 'height': 224.93000000000006}, 'reference_id': 'Batch_20_81685.jpg', 'confidence': 0.8508, 'metadata': {}}]`
`model_run.predict({"annotations": detection})`

**Comment by MaximilianBoemer** [comment]
Uploading annotations works fine at the same time.

Thanks for your help!

**Comment by srikanth-scale** [comment]
Should be fixed per a PR that went out. Will be deployed today in 2 hours ETA.

**Comment by MaximilianBoemer** [comment]
works
