### ISSUE TITLE
Incorrect arguments for call to _process_append_requests_local

### ISSUE THREAD

**Issue by fbcotter** [scaleapi/nucleus-python-client#47]
Running into this error:

```python
pip-dl/pypi__nucleus/nucleus/__init__.py in _process_append_requests_local(self, dataset_id, payload, local_batch_size, size)
    408         request_payloads = []
    409         payload_items = []
--> 410         for i in range(0, len(items), local_batch_size):
    411             batch = items[i : i + local_batch_size]
    412             batch_payload = preprocess_payload(batch)

ValueError: range() arg 3 must not be zero
```
when trying to upload dataset items with `dataset.append`. It looks like it's caused by some bad positional arguments at https://github.com/scaleapi/nucleus-python-client/blob/14f11c48e2b7f4a551a68971f116bf3754856a41/nucleus/__init__.py#L355.

**Comment by srikanth-scale-2** [comment]
Hey! Sorry for the delayed response - we're using slack for support :)

The issue here is that your python client is not up to date - try installing the latest master after uninstalling the current version and try again. Let me know if you face the issue :)

**Comment by rkaplan** [comment]
Closing this because upgrading to the latest Nucleus Python Client resolves the issue.
